---
# tasks file for ipa

  - name: Install ipa, rng-tools, bind-utils
    package:
        name: "{{ item }}"
        state: installed
    with_items:
        - rng-tools
        - bind-utils
        - ipa-server
