---
# tasks file for santa
- name: include setup
  include_role:
      name: setup

- name: set hostname to santa
  hostname:
      name: santa

- name: include dns role
  include_role:
      name: dns
