---
#- hosts: linux
#  ignore_errors: true
#  gather_facts: false
#  vars_files:
#      - vars/common.yml
#  roles:
#      - santa

#- hosts: web
#  ignore_errors: true
#  roles:
#      - web

- hosts: kube
  ignore_errors: true
  roles:
    - wukong