---
# tasks file for radius

  - name: install radius packages
    package:
        name: "{{ item }}"
        state: installed
    with_items:
        - freeradius

  - name: start and enable radius 
    service:
        name: freeradius
        state: started
        enabled: yes
