---
# tasks file for bob
# ubuntu 18.04.2

name: Install builder tools
package:
  name: "{{ item }}"
  state: present
  with_items:
    - python3
    - python3-dev
    - python3-venv
    - gcc
    - libssl-dev
    - autoconf
    - automake
    - libtool
    - vagrant
    - vim
    - virtualbox


# wget https://releases.hashicorp.com/packer/1.4.5/packer_1.4.5_linux_amd64.zip
