---
# tasks file for bob
# ubuntu 18.04.2

name: Install builder tools
package:
  name: "{{ item }}"
  state: present
  with_items:
    - python3
    - python3-dev
    - python3-venv
    - python3-pip
    - gcc
    - libssl-dev
    - autoconf
    - automake
    - libtool
    - vagrant
    - vim
    - virtualbox


- name: Unarchive packer from release
  unarchive:
    src: https://releases.hashicorp.com/packer/1.4.5/packer_1.4.5_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: yes

- name: Install arm builder dependencies
  package:
    name: "{{ item }}"
    state: present
    with_items:
      - kpartx
      - qemu-user-static

- name: Install golang 1.13
  unarchive:
    src: wget https://dl.google.com/go/go1.13.3.linux-amd64.tar.gz
    dest: /usr/local/
