scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'snmp'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.1.45'] # needs changing
    metrics_path: /snmp
    params:
      module: [synology]
      auth: [snmpv3]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - source_labels: [__param_target]
        regex: (.*)
        replacement: snmp-exporter:9116
        target_label: __address__

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'speedtest'
    scrape_interval: 60m
    scrape_timeout:  60s
    metrics_path: /metrics
    static_configs:
      - targets: ['speedtest-exporter:9877']

  # scape tempo metrics
  - job_name: 'tempo'
    static_configs:
      - targets: [ '192.168.1.45:3200' ]

  # Scrape Loki metrics
  - job_name: "loki"
    metrics_path: "/metrics"  # Loki's metrics endpoint
    static_configs:
      - targets: ["192.168.1.45:3100"]  # Replace with your Loki's address and port

  # I seperate these for visibility in prometheus up down detectors of
  # scraping jobs
  - job_name: 'windows REMA windows exporter'
    scrape_interval: 10s
    static_configs:
      - targets: ['192.168.1.80:9182']
    relabel_configs:
      - source_labels: [__address__]
        regex: '([^:]+):\d+'
        target_label: instance
        replacement: 'REMA'

  - job_name: 'windows REMA ohm'
    scrape_interval: 10s
    static_configs:
      - targets: ['192.168.1.80:4445']
    relabel_configs:
      - source_labels: [__address__]
        regex: '([^:]+):\d+'
        target_label: instance
        replacement: 'REMA'

  - job_name: 'windows zoo ohm'
    scrape_interval: 10s
    static_configs:
      - targets: ['192.168.2.80:4445']
    relabel_configs:
      - source_labels: [__address__]
        regex: '([^:]+):\d+'
        target_label: instance
        replacement: 'zoo'